// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'6c248eb862920bd368e30385e7f941dc648cc856c6caba44585b401bb690add6'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AdditionalProjectAspects: {
      readonly projectId: CodecTypes['pg/uuid@1']['output'];
      readonly aspect: Varchar<255> | null;
    };
    readonly DashboardProjects: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly description: Varchar<255> | null;
      readonly name: Varchar<255> | null;
      readonly favorite: CodecTypes['pg/bool@1']['output'] | null;
    };
    readonly DataotterApplicationLink: {
      readonly projectId: CodecTypes['pg/uuid@1']['output'];
      readonly applicationId: CodecTypes['pg/int8@1']['output'] | null;
    };
    readonly GithubProjectLinks: {
      readonly projectId: CodecTypes['pg/uuid@1']['output'];
      readonly githubProjectId: CodecTypes['pg/int8@1']['output'] | null;
    };
    readonly GithubRepositoryLinks: {
      readonly projectId: CodecTypes['pg/uuid@1']['output'];
      readonly githubRepositoryId: CodecTypes['pg/int8@1']['output'] | null;
    };
    readonly MavenProjectLink: {
      readonly projectId: CodecTypes['pg/uuid@1']['output'];
      readonly mavenUrl: Varchar<255> | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AdditionalProjectAspects: {
      readonly projectId: CodecTypes['pg/uuid@1']['input'];
      readonly aspect: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly DashboardProjects: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly name: CodecTypes['sql/varchar@1']['input'] | null;
      readonly favorite: CodecTypes['pg/bool@1']['input'] | null;
    };
    readonly DataotterApplicationLink: {
      readonly projectId: CodecTypes['pg/uuid@1']['input'];
      readonly applicationId: CodecTypes['pg/int8@1']['input'] | null;
    };
    readonly GithubProjectLinks: {
      readonly projectId: CodecTypes['pg/uuid@1']['input'];
      readonly githubProjectId: CodecTypes['pg/int8@1']['input'] | null;
    };
    readonly GithubRepositoryLinks: {
      readonly projectId: CodecTypes['pg/uuid@1']['input'];
      readonly githubRepositoryId: CodecTypes['pg/int8@1']['input'] | null;
    };
    readonly MavenProjectLink: {
      readonly projectId: CodecTypes['pg/uuid@1']['input'];
      readonly mavenUrl: CodecTypes['sql/varchar@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly additional_project_aspects: {
      readonly aspect: Varchar<255> | null;
      readonly project_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly dashboard_projects: {
      readonly description: Varchar<255> | null;
      readonly favorite: CodecTypes['pg/bool@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: Varchar<255> | null;
    };
    readonly dataotter_application_link: {
      readonly application_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly github_project_links: {
      readonly github_project_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly github_repository_links: {
      readonly github_repository_id: CodecTypes['pg/int8@1']['output'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly maven_project_link: {
      readonly maven_url: Varchar<255> | null;
      readonly project_id: CodecTypes['pg/uuid@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly additional_project_aspects: {
      readonly aspect: CodecTypes['sql/varchar@1']['input'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly dashboard_projects: {
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly favorite: CodecTypes['pg/bool@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly dataotter_application_link: {
      readonly application_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly github_project_links: {
      readonly github_project_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly github_repository_links: {
      readonly github_repository_id: CodecTypes['pg/int8@1']['input'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly maven_project_link: {
      readonly maven_url: CodecTypes['sql/varchar@1']['input'] | null;
      readonly project_id: CodecTypes['pg/uuid@1']['input'];
    };
  };
};

export namespace Models {
  export type public_DashboardProjects = {
    id: CodecTypes['pg/uuid@1']['output'];
    description: Varchar<255> | null;
    name: Varchar<255> | null;
    favorite: CodecTypes['pg/bool@1']['output'] | null;
    additionalProjectAspects: public_AdditionalProjectAspects[];
    dataotterApplicationLinks: public_DataotterApplicationLink[];
    githubProjectLinks: public_GithubProjectLinks[];
    githubRepositoryLinks: public_GithubRepositoryLinks[];
    mavenProjectLinks: public_MavenProjectLink[];
    readonly [RelationKeys]?:
      | 'additionalProjectAspects'
      | 'dataotterApplicationLinks'
      | 'githubProjectLinks'
      | 'githubRepositoryLinks'
      | 'mavenProjectLinks';
  };
  export type public_AdditionalProjectAspects = {
    projectId: CodecTypes['pg/uuid@1']['output'];
    aspect: Varchar<255> | null;
    project: public_DashboardProjects;
    readonly [RelationKeys]?: 'project';
  };
  export type public_DataotterApplicationLink = {
    projectId: CodecTypes['pg/uuid@1']['output'];
    applicationId: CodecTypes['pg/int8@1']['output'] | null;
    project: public_DashboardProjects;
    readonly [RelationKeys]?: 'project';
  };
  export type public_GithubProjectLinks = {
    projectId: CodecTypes['pg/uuid@1']['output'];
    githubProjectId: CodecTypes['pg/int8@1']['output'] | null;
    project: public_DashboardProjects;
    readonly [RelationKeys]?: 'project';
  };
  export type public_GithubRepositoryLinks = {
    projectId: CodecTypes['pg/uuid@1']['output'];
    githubRepositoryId: CodecTypes['pg/int8@1']['output'] | null;
    project: public_DashboardProjects;
    readonly [RelationKeys]?: 'project';
  };
  export type public_MavenProjectLink = {
    projectId: CodecTypes['pg/uuid@1']['output'];
    mavenUrl: Varchar<255> | null;
    project: public_DashboardProjects;
    readonly [RelationKeys]?: 'project';
  };
}

export declare const models: {
  public: {
    DashboardProjects: Models.public_DashboardProjects;
    AdditionalProjectAspects: Models.public_AdditionalProjectAspects;
    DataotterApplicationLink: Models.public_DataotterApplicationLink;
    GithubProjectLinks: Models.public_GithubProjectLinks;
    GithubRepositoryLinks: Models.public_GithubRepositoryLinks;
    MavenProjectLink: Models.public_MavenProjectLink;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly additional_project_aspects: {
              columns: {
                readonly project_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly aspect: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'additional_project_aspects';
                    readonly columns: readonly ['project_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dashboard_projects';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'fk60wy1ni71ddy0tl4sllg47ljh';
                },
              ];
            };
            readonly dashboard_projects: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly favorite: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'dashboard_projects_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly dataotter_application_link: {
              columns: {
                readonly project_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly application_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dataotter_application_link';
                    readonly columns: readonly ['project_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dashboard_projects';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'fkmk4turc23fe3pvrk0vmc9ligi';
                },
              ];
            };
            readonly github_project_links: {
              columns: {
                readonly project_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly github_project_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'github_project_links';
                    readonly columns: readonly ['project_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dashboard_projects';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'fk29na5lvj3s2nf61jdtf2a8sxs';
                },
              ];
            };
            readonly github_repository_links: {
              columns: {
                readonly project_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly github_repository_id: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8@1';
                  readonly nullable: true;
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'github_repository_links';
                    readonly columns: readonly ['project_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dashboard_projects';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'fkn45dxtnp0paps1mofyflpu7ej';
                },
              ];
            };
            readonly maven_project_link: {
              columns: {
                readonly project_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly maven_url: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'maven_project_link';
                    readonly columns: readonly ['project_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'dashboard_projects';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'fkl1d5x2v3gmw43vpw1tepn2sjy';
                },
              ];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly dashboard_projects: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DashboardProjects';
    };
    readonly additional_project_aspects: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AdditionalProjectAspects';
    };
    readonly dataotter_application_link: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DataotterApplicationLink';
    };
    readonly github_project_links: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'GithubProjectLinks';
    };
    readonly github_repository_links: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'GithubRepositoryLinks';
    };
    readonly maven_project_link: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MavenProjectLink';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AdditionalProjectAspects: {
            readonly fields: {
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly aspect: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DashboardProjects';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'additional_project_aspects';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly projectId: { readonly column: 'project_id' };
                readonly aspect: { readonly column: 'aspect' };
              };
            };
          };
          readonly DashboardProjects: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly name: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly favorite: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: {
              readonly additionalProjectAspects: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AdditionalProjectAspects';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
              readonly dataotterApplicationLinks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DataotterApplicationLink';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
              readonly githubProjectLinks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GithubProjectLinks';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
              readonly githubRepositoryLinks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'GithubRepositoryLinks';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
              readonly mavenProjectLinks: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MavenProjectLink';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['projectId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'dashboard_projects';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly description: { readonly column: 'description' };
                readonly name: { readonly column: 'name' };
                readonly favorite: { readonly column: 'favorite' };
              };
            };
          };
          readonly DataotterApplicationLink: {
            readonly fields: {
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly applicationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DashboardProjects';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'dataotter_application_link';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly projectId: { readonly column: 'project_id' };
                readonly applicationId: { readonly column: 'application_id' };
              };
            };
          };
          readonly GithubProjectLinks: {
            readonly fields: {
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly githubProjectId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DashboardProjects';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'github_project_links';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly projectId: { readonly column: 'project_id' };
                readonly githubProjectId: { readonly column: 'github_project_id' };
              };
            };
          };
          readonly GithubRepositoryLinks: {
            readonly fields: {
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly githubRepositoryId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8@1' };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DashboardProjects';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'github_repository_links';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly projectId: { readonly column: 'project_id' };
                readonly githubRepositoryId: { readonly column: 'github_repository_id' };
              };
            };
          };
          readonly MavenProjectLink: {
            readonly fields: {
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly mavenUrl: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly project: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DashboardProjects';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['projectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'maven_project_link';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly projectId: { readonly column: 'project_id' };
                readonly mavenUrl: { readonly column: 'maven_url' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
