name: React-Website

on:
  push:
    branches: [master]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-react-deploy.yaml@v1.0.1
    with:
      environment: production
      deploymentName: website
      imageName: website-react